# Generated by Django 3.1 on 2020-08-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='body',
            field=models.TextField(max_length=200),
        ),
    ]
